# Generated by Django 2.2.1 on 2019-06-07 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chiffre1', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=100)),
                ('chiffre2', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
